### ISSUE TITLE
Main Issue from DayCareManagement System

### ISSUE THREAD

**Issue by 1141123832** [1141125335/Group9_DayCareManagementSystem#2]
1. The result should be gallery
2. The add child page need to has the same header (The menubar)
3. The gallery page can like adding select a gallery name, select that image is belong to which child. Then parent can view the gallery by filtering he want to look his child photo
4.Profile page
5.remove the permission tab

**Comment by SouIBlood** [comment]
Hi, I have fixed merged the first  issue. #3

**Comment by SouIBlood** [comment]
#4 For the 2nd issue

**Comment by SouIBlood** [comment]
#6 For 5th issue

**Comment by SouIBlood** [comment]
#7 For 3rd issue improvement

**Comment by SouIBlood** [comment]
#11 For 4th issue
